### ISSUE TITLE
项目跑不起来啊

### ISSUE THREAD

**Issue by tomorrowNicest** [aiplat/uniapp#7]

**Comment by TonyLuo** [comment]
```
tony$ npm run dev

> aiplat.com-miniprogram@1.1.1 dev /Users/tony/dev/uni-app/uniapp
> node build.config.js && cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch

(node:11492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at isIn (/Users/tony/dev/uni-app/uniapp/build.config.js:21:9)
    at configArgv (/Users/tony/dev/uni-app/uniapp/build.config.js:50:13)
    at Object.<anonymous> (/Users/tony/dev/uni-app/uniapp/build.config.js:85:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:11492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by aiplat** [comment]
拉取下代码 重新试下
